### ISSUE TITLE
Provide Maven dependency?

### ISSUE THREAD

**Issue by philipparndt** [manpreet333/apache-sseclient#5]
Hi @manpreet333 

Thanks for this project 👍 

I like to use it in one of my projects (https://github.com/philipparndt/miele-to-mqtt-gw).
Currently, I just copied your sources and added a link in the JavaDoc comment.
It would be great when you could provide a maven dependency.

**Comment by preet-dev** [comment]
Hey @philipparndt 

Sorry about the late response. I had not published to maven before and a bunch of things got in the way.
You should now be available to import it using the coordinates `'dev.manpreet:apache-sseclient:1.0'`

Thank you

**Comment by philipparndt** [comment]
Thank you :)
