### ISSUE TITLE
Improvement: Utilization of "future.isDone().

### ISSUE THREAD

**Issue by uizuKim** [manpreet333/apache-sseclient#6]
https://github.com/autopreet/apache-sseclient/blob/c3e6de2c106c13c0dba382a0050c47ab68a2921f/src/main/java/dev/manpreet/apache/sseclient/ApacheHttpSseClient.java#L55-L70

Performing ".complete(...)" verifies that the "future.isDone()" status has been processed incorrectly.

I think it is safe for the client to perform ".complete(..)" when the server's http is closed.

------------------------------------------

  @Override
  protected void onResponseReceived(HttpResponse response) {
      this.response = new SseResponse(response);
//      futureResp.complete(this.response);
  }

# Add

    @Override
    protected void releaseResources(){
        futureResp.complete(this.response);
    }

---
TEST CODE 

  SseRequest sseRequest = new SseRequest(SSEUri);
  Future<SseResponse> sseResponseFuture = sseClient.execute(sseRequest);

  while ( sseResponseFuture.isDone() == false ){
      try{
          Thread.sleep( 100L );
      }catch(Exception e ){}
  }

**Comment by preet-dev** [comment]
Thank you for the improvement suggestion.
