### ISSUE TITLE
Improvement:  for java 1.8 

### ISSUE THREAD

**Issue by uizuKim** [manpreet333/apache-sseclient#7]
https://github.com/autopreet/apache-sseclient/blob/c3e6de2c106c13c0dba382a0050c47ab68a2921f/src/main/java/dev/manpreet/apache/sseclient/SseEntity.java#L50

BufferedReader rawEvent = new BufferedReader(new StringReader( currentEvent.toString() ));

**Comment by preet-dev** [comment]
The code constructing `currentEvent` and using it is all String based. Did not understand why we would need `BufferedReader`. Kindly elaborate.

**Comment by preet-dev** [comment]
I will be closing this out. Please reach out or open another issue in case I missed something.
